# Generated by Django 4.2.5 on 2023-10-06 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_categorymodel_alter_productmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Все продукты'},
        ),
        migrations.AddField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.categorymodel'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
